//! Statement-level coverage: every individual thing the specification says you
//! must be able to do, mapped to the topic that teaches it.
//!
//! The reference list in `course.rs` proves no *section* of a specification is
//! missing. This goes a level finer: 4MA1 breaks each reference into lettered
//! statements, and this table has one entry per statement, so the app can show
//! a checklist of everything rather than asking you to trust that a topic
//! "covers" its reference.
//!
//! The letters and their count were extracted mechanically from the
//! specification PDF, not typed from memory — the lettering runs A, B, C... per
//! reference, so a dropped statement shows up as a gap in the sequence.
//! `F` prefixes a Foundation Tier statement, `H` a Higher Tier one; Higher
//! assumes all of the Foundation content, so both are studied.
//!
//! The labels are short factual descriptions written for this app. The
//! specification's own wording is Pearson's copyright and is not reproduced —
//! each topic links to the official document so you can read the real text.

/// (topic code, statement code, what it is)
pub const MATHS: &[(&str, &str, &str)] = &[
    // 1.1 Integers
    ("1.1", "FA", "Positive, negative and zero integers"),
    ("1.1", "FB", "Place value"),
    ("1.1", "FC", "Directed numbers in context, such as temperature"),
    ("1.1", "FD", "Ordering integers"),
    ("1.1", "FE", "The four rules"),
    ("1.1", "FF", "Brackets and the order of operations"),
    ("1.1", "FG", "Odd, even, prime, factor and multiple"),
    ("1.1", "FH", "Prime factors, common factors and common multiples"),
    // 1.2 Fractions
    ("1.2", "FA", "Equivalent fractions and simplifying"),
    ("1.2", "FB", "Mixed numbers and improper fractions"),
    ("1.2", "FC", "Common denominators"),
    ("1.2", "FD", "Ordering fractions, and a fraction of a quantity"),
    ("1.2", "FE", "One number as a fraction of another"),
    ("1.2", "FF", "Adding and subtracting fractions and mixed numbers"),
    ("1.2", "FG", "Fraction to decimal or percentage"),
    ("1.2", "FH", "Unit fractions as multiplicative inverses"),
    ("1.2", "FI", "Multiplying and dividing fractions and mixed numbers"),
    // 1.3 Decimals
    ("1.3", "FA", "Decimal notation"),
    ("1.3", "FB", "Place value in decimals"),
    ("1.3", "FC", "Ordering decimals"),
    ("1.3", "FD", "Decimal to fraction or percentage"),
    ("1.3", "FE", "Why a terminating decimal is a fraction"),
    ("1.3", "HA", "Recurring decimals to fractions"),
    // 1.4 Powers, roots and surds
    ("1.4a", "FA", "Square and cube numbers"),
    ("1.4a", "FB", "Squares, cubes and their roots"),
    ("1.4a", "FC", "Index notation and the index laws"),
    ("1.4a", "FD", "Integers as a product of prime powers"),
    ("1.4a", "FE", "Highest common factor and lowest common multiple"),
    ("1.4a", "HC", "Index laws with fractional and negative powers"),
    ("1.4b", "HA", "What a surd is"),
    ("1.4b", "HB", "Manipulating surds and rationalising a denominator"),
    // 1.5 Sets
    ("1.5", "FA", "What a set is"),
    ("1.5", "FB", "Set notation"),
    ("1.5", "FC", "The universal set and the empty set"),
    ("1.5", "FD", "The complement of a set"),
    ("1.5", "FE", "Venn diagrams"),
    ("1.5", "HA", "Sets defined algebraically, and subsets"),
    ("1.5", "HB", "Venn diagrams for sets and the number of elements"),
    ("1.5", "HC", "The notation n(A)"),
    ("1.5", "HD", "Sets in practical situations"),
    // 1.6 Percentages
    ("1.6", "FA", "Percentage as parts per hundred"),
    ("1.6", "FB", "One number as a percentage of another"),
    ("1.6", "FC", "Percentage as a fraction and as a decimal"),
    ("1.6", "FD", "Percentages as multiplicative operators"),
    ("1.6", "FE", "Percentage increase and decrease"),
    ("1.6", "FF", "Reverse percentages"),
    ("1.6", "FG", "Compound interest and depreciation"),
    ("1.6", "HA", "Repeated percentage change"),
    ("1.6", "HB", "Compound interest problems"),
    // 1.7 Ratio and proportion
    ("1.7", "FA", "Ratio notation and simplifying"),
    ("1.7", "FB", "Dividing a quantity in a ratio"),
    ("1.7", "FC", "Proportionality to find unknown quantities"),
    ("1.7", "FD", "Quantities in direct proportion"),
    ("1.7", "FE", "Word problems on ratio and proportion"),
    // 1.8 Accuracy and bounds
    ("1.8", "FA", "Rounding to a power of ten"),
    ("1.8", "FB", "Significant figures and decimal places"),
    ("1.8", "FC", "Upper and lower bounds"),
    ("1.8", "FD", "Estimating a calculation"),
    ("1.8", "HA", "Problems using upper and lower bounds"),
    // 1.9 Standard form
    ("1.9", "FA", "Calculating with numbers in standard form"),
    ("1.9", "HA", "Problems involving standard form"),
    // 1.10 Applying number
    ("1.10", "FA", "Number in everyday life"),
    ("1.10", "FB", "Standard units of mass, length, area, volume and capacity"),
    ("1.10", "FC", "Time, money and currency conversion"),
    // 1.11 Calculators
    ("1.11", "FA", "Using a scientific calculator"),
    // 2.1 Use of symbols
    ("2.1", "FA", "Symbols for numbers and variables"),
    ("2.1", "FB", "Algebra follows the rules of arithmetic"),
    ("2.1", "FC", "Index notation with positive and negative powers"),
    ("2.1", "FD", "Index laws in simple cases"),
    ("2.1", "HA", "Index notation with fractional, negative and zero powers"),
    // 2.2 Algebraic manipulation
    ("2.2a", "FA", "Evaluating expressions by substitution"),
    ("2.2a", "FB", "Collecting like terms"),
    ("2.2a", "FC", "Multiplying a single term over a bracket"),
    ("2.2a", "FD", "Taking out common factors"),
    ("2.2a", "FE", "Expanding two linear brackets"),
    ("2.2a", "FF", "Factorising simple quadratics"),
    ("2.2a", "HA", "Expanding two or more linear expressions"),
    ("2.2a", "HB", "Factorising harder quadratics"),
    ("2.2b", "HC", "Algebraic fractions"),
    ("2.2b", "HD", "Completing the square"),
    ("2.2b", "HE", "Algebraic proof"),
    // 2.3 Expressions and formulae
    ("2.3", "FA", "A letter as an unknown or a variable"),
    ("2.3", "FB", "Notational conventions"),
    ("2.3", "FC", "Substituting integers, decimals and fractions"),
    ("2.3", "FD", "Formulae from words or diagrams"),
    ("2.3", "FE", "Deriving a formula or expression"),
    ("2.3", "FF", "Changing the subject when it appears once"),
    ("2.3", "HA", "Changing the subject when it appears twice or as a power"),
    // 2.4 Linear equations
    ("2.4", "FA", "Solving linear equations"),
    ("2.4", "FB", "Setting up linear equations from given data"),
    // 2.5 Proportion
    ("2.5", "HA", "Direct and inverse proportion, and their graphs"),
    // 2.6 Simultaneous equations
    ("2.6", "FA", "Exact solution of two simultaneous equations"),
    ("2.6", "HA", "Exact solution of two simultaneous equations"),
    ("2.6", "HB", "Solutions as the intersection of two lines"),
    // 2.7 Quadratic equations
    ("2.7a", "FA", "Solving quadratics by factorising"),
    ("2.7a", "HA", "Solving quadratics by factorising"),
    ("2.7a", "HB", "Solving by formula or completing the square"),
    ("2.7b", "HC", "Forming and solving quadratics from context"),
    ("2.7b", "HD", "One linear and one quadratic simultaneously"),
    // 2.8 Inequalities
    ("2.8", "FA", "The inequality symbols"),
    ("2.8", "FB", "Open and closed intervals on a number line"),
    ("2.8", "FC", "Solving linear inequalities and showing the solution set"),
    ("2.8", "FD", "Linear inequalities on a graph"),
    ("2.8", "FE", "Regions defined by linear inequalities"),
    ("2.8", "HA", "Quadratic inequalities and their solution set"),
    ("2.8", "HB", "Harder regions defined by linear inequalities"),
    // 3.1 Sequences and series
    ("3.1a", "FA", "Generating terms of a sequence"),
    ("3.1a", "FB", "Later terms, and the rule that makes them"),
    ("3.1a", "FC", "The nth term of an arithmetic sequence"),
    ("3.1b", "HA", "First term and common difference"),
    ("3.1b", "HB", "The nth term as a + (n − 1)d"),
    ("3.1b", "HC", "The sum of the first n terms"),
    // 3.2 Functions
    ("3.2", "HA", "A function as a mapping between two sets"),
    ("3.2", "HB", "Function notation"),
    ("3.2", "HC", "Domain, range, and excluded values"),
    ("3.2", "HD", "Composite and inverse functions"),
    // 3.3 Graphs
    ("3.3a", "FA", "Interpreting linear and non-linear graphs"),
    ("3.3a", "FB", "Cartesian coordinate conventions"),
    ("3.3a", "FC", "Plotting points in all four quadrants"),
    ("3.3a", "FD", "Coordinates from geometrical information"),
    ("3.3a", "FE", "The midpoint of a line segment"),
    ("3.3a", "FF", "Straight-line conversion graphs"),
    ("3.3a", "FG", "The gradient of a straight line"),
    ("3.3a", "FH", "y = mx + c as gradient and intercept"),
    ("3.3a", "HF", "Gradient from the coordinates of two points"),
    ("3.3a", "HG", "Equations of parallel and perpendicular lines"),
    ("3.3b", "FI", "Plotting linear and quadratic graphs"),
    ("3.3b", "HA", "Cubic, reciprocal and trigonometric graphs"),
    ("3.3c", "HB", "Transformations of y = f(x)"),
    ("3.3c", "HC", "Writing a transformed function algebraically"),
    ("3.3c", "HD", "Gradient of a curve by drawing a tangent"),
    ("3.3c", "HE", "Intersections of a line and a curve as solutions"),
    // 3.4 Calculus
    ("3.4", "HA", "A variable rate of change"),
    ("3.4", "HB", "Differentiating integer powers of x"),
    ("3.4", "HC", "Gradients, rates of change and stationary points"),
    ("3.4", "HD", "Telling maxima from minima"),
    ("3.4", "HE", "Calculus applied to kinematics"),
    // 4.1 Angles, lines and triangles
    ("4.1", "FA", "Acute, obtuse, reflex and right angles"),
    ("4.1", "FB", "Angles on intersecting and parallel lines"),
    ("4.1", "FC", "Angle sum and exterior angle of a triangle"),
    ("4.1", "FD", "Isosceles, equilateral and right-angled triangles"),
    // 4.2 Polygons
    ("4.2", "FA", "Naming polygons"),
    ("4.2", "FB", "Angle sum of a quadrilateral"),
    ("4.2", "FC", "Properties of the special quadrilaterals"),
    ("4.2", "FD", "Interior and exterior angles of a regular polygon"),
    ("4.2", "FE", "Angle sum of a polygon"),
    ("4.2", "FF", "Congruence as same shape and size"),
    ("4.2", "FG", "Recognising congruent polygons"),
    // 4.3 Symmetry
    ("4.3", "FA", "Lines of symmetry and order of rotational symmetry"),
    // 4.4 Measures
    ("4.4", "FA", "Reading scales on measuring instruments"),
    ("4.4", "FB", "Time intervals on the 12- and 24-hour clock"),
    ("4.4", "FC", "Sensible estimates of measures"),
    ("4.4", "FD", "Angle measure and three-figure bearings"),
    ("4.4", "FE", "Measuring an angle to the nearest degree"),
    ("4.4", "FF", "Average speed, distance and time"),
    ("4.4", "FG", "Compound measures: speed, density and pressure"),
    // 4.5 Construction
    ("4.5", "FA", "Measuring and drawing to the nearest millimetre"),
    ("4.5", "FB", "Constructing triangles and other shapes"),
    ("4.5", "FC", "Problems using scale drawings"),
    ("4.5", "FD", "Perpendicular and angle bisectors with compasses"),
    // 4.6 Circles
    ("4.6", "FA", "The parts of a circle by name"),
    ("4.6", "FB", "Chord and tangent properties"),
    ("4.6", "HA", "Internal and external intersecting chords"),
    ("4.6", "HB", "Cyclic quadrilaterals"),
    ("4.6", "HC", "The circle theorems, including alternate segment"),
    // 4.7 Geometrical reasoning
    ("4.7", "FA", "Informal reasons for a geometrical answer"),
    ("4.7", "HA", "Standard geometrical statements as reasons"),
    // 4.8 Pythagoras and trigonometry
    ("4.8a", "FA", "Pythagoras in two dimensions"),
    ("4.8a", "FB", "Sine, cosine and tangent of acute angles"),
    ("4.8a", "FC", "Trigonometry applied in two dimensions"),
    ("4.8a", "HB", "Angles of elevation and depression"),
    ("4.8b", "HA", "Sine, cosine and tangent of obtuse angles"),
    ("4.8b", "HC", "The sine and cosine rules"),
    ("4.8b", "HE", "Area of a triangle as ½ab sin C"),
    ("4.8c", "HD", "Pythagoras in three dimensions"),
    ("4.8c", "HF", "Trigonometry in three dimensions, and line-to-plane angles"),
    // 4.9 Mensuration
    ("4.9", "FA", "Converting linear and area units"),
    ("4.9", "FB", "Perimeter of shapes made from triangles and rectangles"),
    ("4.9", "FC", "Area of triangles and rectangles"),
    ("4.9", "FD", "Area of parallelograms and trapezia"),
    ("4.9", "FE", "Circumference and area of circles and semicircles"),
    ("4.9", "HA", "Perimeter and area of a sector"),
    // 4.10 3D shapes
    ("4.10", "FA", "Naming solids"),
    ("4.10", "FB", "Face, edge and vertex"),
    ("4.10", "FC", "Surface area of simple solids"),
    ("4.10", "FD", "Surface area of a cylinder"),
    ("4.10", "FE", "Volume of prisms, cuboids and cylinders"),
    ("4.10", "FF", "Converting units of volume"),
    ("4.10", "HA", "Surface area and volume of a sphere and a cone"),
    // 4.11 Similarity
    ("4.11", "FA", "Similar figures: lengths in ratio, angles unchanged"),
    ("4.11", "FB", "Maps and scale drawings"),
    ("4.11", "HA", "Areas of similar figures scale by k²"),
    ("4.11", "HB", "Volumes of similar figures scale by k³"),
    ("4.11", "HC", "Using area and volume scale factors to solve problems"),
    // 5.1 Vectors
    ("5.1", "HA", "A vector has magnitude and direction"),
    ("5.1", "HB", "Vector notation, including column vectors"),
    ("5.1", "HC", "Multiplying a vector by a scalar"),
    ("5.1", "HD", "Adding and subtracting vectors"),
    ("5.1", "HE", "The modulus of a vector"),
    ("5.1", "HF", "The resultant of two or more vectors"),
    ("5.1", "HG", "Vectors in simple geometrical proofs"),
    // 5.2 Transformations
    ("5.2", "FA", "A rotation is given by a centre and an angle"),
    ("5.2", "FB", "Rotating a shape about a point"),
    ("5.2", "FC", "Anticlockwise as positive, clockwise as negative"),
    ("5.2", "FD", "A reflection is given by a mirror line"),
    ("5.2", "FE", "Constructing a mirror line, and reflecting"),
    ("5.2", "FF", "A translation is given by distance and direction"),
    ("5.2", "FG", "Translating a shape"),
    ("5.2", "FH", "Column vectors for translations"),
    ("5.2", "FI", "Rotation, reflection and translation preserve congruence"),
    ("5.2", "FJ", "An enlargement is given by a centre and a scale factor"),
    ("5.2", "FK", "Enlargement preserves angles but not lengths"),
    ("5.2", "FL", "Enlarging a shape by a scale factor"),
    ("5.2", "FM", "Giving a complete description of a transformation"),
    // 6.1 Presenting data
    ("6.1a", "FA", "Pictograms, bar charts and pie charts"),
    ("6.1a", "FB", "Tabulating data, including two-way tables"),
    ("6.1a", "FC", "Interpreting statistical diagrams"),
    ("6.1b", "HA", "Constructing and interpreting histograms"),
    ("6.1c", "HB", "Constructing cumulative frequency diagrams"),
    ("6.1c", "HC", "Using cumulative frequency diagrams"),
    // 6.2 Statistical measures
    ("6.2", "FA", "What an average is"),
    ("6.2", "FB", "Mean, median, mode and range"),
    ("6.2", "FC", "Estimated mean of grouped data"),
    ("6.2", "FD", "The modal class"),
    ("6.2", "HA", "Median from a cumulative frequency diagram"),
    ("6.2", "HB", "What a measure of spread is"),
    ("6.2", "HC", "Interquartile range of a discrete data set"),
    ("6.2", "HD", "Interquartile range from a cumulative frequency diagram"),
    // 6.3 Probability
    ("6.3a", "FA", "The language of probability"),
    ("6.3a", "FB", "The probability scale"),
    ("6.3a", "FC", "Probability from a theoretical model"),
    ("6.3a", "FD", "Probability from a Venn diagram"),
    ("6.3a", "FE", "Sample space and event"),
    ("6.3a", "FF", "Listing outcomes systematically"),
    ("6.3a", "FG", "Estimating probability from collected data"),
    ("6.3a", "FH", "The probability of the complement"),
    ("6.3a", "FI", "The addition rule for mutually exclusive events"),
    ("6.3a", "FJ", "Expected frequency"),
    ("6.3b", "HA", "Tree diagrams"),
    ("6.3b", "HB", "Two or more independent events"),
    ("6.3b", "HC", "Conditional probability"),
    ("6.3b", "HD", "Probability applied to problems"),
];


/// Biology 4BI1. Statements are numbered section.n; a `B` suffix marks
/// separate-science-only content (Double Award students skip it).
/// (topic code, statement code, what it is)
pub const BIO: &[(&str, &str, &str)] = &[
    // 1 Nature and variety of living organisms
    ("1a", "1.1", "The characteristics shared by all living organisms"),
    ("1a", "1.2", "Common features of eukaryotes: plants, animals, fungi, protoctists"),
    ("1a", "1.3", "Common features of prokaryotes such as bacteria"),
    ("1a", "1.4", "Pathogens, and the groups they can come from"),
    // 2 Structures and functions in living organisms
    ("2a", "2.1", "Levels of organisation from organelle to organism"),
    ("2a", "2.2", "The structures in a cell"),
    ("2a", "2.3", "What each cell structure does"),
    ("2a", "2.4", "Plant and animal cells compared"),
    ("2a", "2.5B", "Why cell differentiation matters in developing specialised cells"),
    ("2a", "2.6B", "Stem cells in medicine: for and against"),
    ("2b", "2.7", "The elements in carbohydrates, proteins and lipids"),
    ("2b", "2.8", "Large molecules built from smaller units"),
    ("2b", "2.9", "Practical: food tests for glucose, starch, protein and fat"),
    ("2b", "2.10", "Enzymes as biological catalysts"),
    ("2b", "2.11", "The effect of temperature on enzymes, including denaturing"),
    ("2b", "2.12", "Practical: enzyme activity and temperature"),
    ("2b", "2.13", "The effect of pH on the active site"),
    ("2b", "2.14B", "Practical: enzyme activity and pH"),
    ("2c", "2.15", "Diffusion, osmosis and active transport"),
    ("2c", "2.16", "What affects the rate of movement into and out of cells"),
    ("2c", "2.17", "Practical: diffusion and osmosis in living and non-living systems"),
    ("2d", "2.18", "Photosynthesis and what it converts"),
    ("2d", "2.19", "The word and symbol equations for photosynthesis"),
    ("2d", "2.20", "Carbon dioxide, light and temperature as limiting factors"),
    ("2d", "2.21", "Leaf structure and its adaptations for photosynthesis"),
    ("2d", "2.22", "Mineral ions plants need: magnesium and nitrate"),
    ("2d", "2.23", "Practical: photosynthesis experiments"),
    ("2e", "2.24", "What a balanced diet contains"),
    ("2e", "2.25", "Sources and functions of each nutrient"),
    ("2e", "2.26", "How energy needs vary with activity, age and pregnancy"),
    ("2e", "2.27", "The alimentary canal: structure and function"),
    ("2e", "2.28", "Peristalsis"),
    ("2e", "2.29", "Digestive enzymes and what each breaks down"),
    ("2e", "2.30", "Where bile is made and stored"),
    ("2e", "2.31", "What bile does: neutralising acid, emulsifying lipids"),
    ("2e", "2.32", "How the small intestine is adapted for absorption"),
    ("2e", "2.33B", "Practical: the energy content of a food sample"),
    ("2f", "2.34", "Respiration produces ATP"),
    ("2f", "2.35", "ATP as the cell's energy supply"),
    ("2f", "2.36", "Aerobic and anaerobic respiration compared"),
    ("2f", "2.37", "The word and symbol equations for aerobic respiration"),
    ("2f", "2.38", "The word equations for anaerobic respiration in plants and animals"),
    ("2f", "2.39", "Practical: carbon dioxide and heat from respiring seeds"),
    ("2g", "2.40B", "Diffusion in gas exchange"),
    ("2g", "2.41B", "Gas exchange and the balance of photosynthesis and respiration"),
    ("2g", "2.42B", "Leaf adaptations for gas exchange"),
    ("2g", "2.43B", "The role of stomata"),
    ("2g", "2.44B", "Respiration by day and night, and net gas exchange"),
    ("2g", "2.45B", "Practical: light and net gas exchange from a leaf"),
    ("2h", "2.46", "The structure of the thorax"),
    ("2h", "2.47", "Intercostal muscles and the diaphragm in ventilation"),
    ("2h", "2.48", "How alveoli are adapted for gas exchange"),
    ("2h", "2.49", "The consequences of smoking for lungs and circulation"),
    ("2h", "2.50", "Practical: breathing and carbon dioxide release"),
    ("2i", "2.51", "Why unicellular organisms can rely on diffusion"),
    ("2i", "2.52", "Why multicellular organisms need a transport system"),
    ("2i", "2.53", "Phloem: carrying sucrose and amino acids"),
    ("2i", "2.54", "Xylem: carrying water and mineral ions"),
    ("2i", "2.55B", "Water uptake by root hair cells"),
    ("2i", "2.56B", "Transpiration defined"),
    ("2i", "2.57B", "What affects the rate of transpiration"),
    ("2i", "2.58B", "Practical: environmental factors and water uptake"),
    ("2j", "2.59", "The composition of blood"),
    ("2j", "2.60", "What plasma transports"),
    ("2j", "2.61", "Red blood cell adaptations for carrying oxygen"),
    ("2j", "2.62", "The immune response: white blood cells and antibodies"),
    ("2j", "2.63B", "Vaccination and memory cells"),
    ("2j", "2.64B", "Platelets and clotting"),
    ("2k", "2.65", "The structure of the heart and how it works"),
    ("2k", "2.66", "Heart rate in exercise and under adrenaline"),
    ("2k", "2.67", "Risk factors for coronary heart disease"),
    ("2k", "2.68", "Arteries, veins and capillaries: structure and function"),
    ("2k", "2.69", "The layout of the circulation"),
    ("2l", "2.70", "Carbon dioxide and oxygen as waste products of metabolism"),
    ("2l", "2.71", "The excretory products of lungs, kidneys and skin"),
    ("2l", "2.72B", "The kidney's roles: excretion and osmoregulation"),
    ("2l", "2.73B", "The structure of the urinary system"),
    ("2l", "2.74B", "The structure of a nephron"),
    ("2l", "2.75B", "Ultrafiltration and the glomerular filtrate"),
    ("2l", "2.76B", "Water reabsorption in the collecting duct"),
    ("2l", "2.77B", "Selective reabsorption of glucose"),
    ("2l", "2.78B", "ADH and the water content of the blood"),
    ("2l", "2.79B", "What urine contains"),
    ("2m", "2.80", "How organisms respond to their environment"),
    ("2m", "2.81", "Homeostasis defined"),
    ("2m", "2.82", "Stimulus, receptor, coordinator, effector, response"),
    ("2m", "2.83", "Plants respond to stimuli"),
    ("2m", "2.84", "Geotropism and phototropism in roots and stems"),
    ("2m", "2.85", "Auxin and the phototropic response"),
    ("2m", "2.93", "The skin in temperature regulation"),
    ("2n", "2.87", "The central nervous system: brain and spinal cord"),
    ("2n", "2.88", "Receptors, impulses and the nervous pathway"),
    ("2n", "2.89", "Neurotransmitters at synapses"),
    ("2n", "2.90", "The reflex arc"),
    ("2n", "2.91", "The structure and function of the eye"),
    ("2n", "2.92", "Focusing on near and distant objects, and light and dark"),
    ("2o", "2.86", "Nervous and hormonal control compared"),
    ("2o", "2.94", "Adrenaline, insulin, testosterone, progesterone, oestrogen: sources, roles, effects"),
    ("2o", "2.95B", "ADH, FSH and LH: sources, roles, effects"),
    // 3 Reproduction and inheritance
    ("3a", "3.1", "Sexual and asexual reproduction compared"),
    ("3a", "3.2", "Fertilisation as the fusion of gametes"),
    ("3a", "3.3", "Insect- and wind-pollinated flowers"),
    ("3a", "3.4", "The pollen tube, fertilisation, seed and fruit"),
    ("3a", "3.5", "Practical: conditions for germination"),
    ("3a", "3.6", "How germinating seeds use their food reserves"),
    ("3a", "3.7", "Natural asexual reproduction in plants"),
    ("3b", "3.8", "Male and female reproductive systems and their adaptations"),
    ("3b", "3.9", "Oestrogen and progesterone in the menstrual cycle"),
    ("3b", "3.10B", "FSH and LH in the menstrual cycle"),
    ("3b", "3.11", "The placenta and the nutrition of the embryo"),
    ("3b", "3.12", "Amniotic fluid protecting the embryo"),
    ("3b", "3.13", "Oestrogen and testosterone and secondary sexual characteristics"),
    ("3c", "3.14", "The genome and the gene"),
    ("3c", "3.15", "Chromosomes carry genes"),
    ("3c", "3.16B", "DNA as a double helix of complementary bases"),
    ("3c", "3.17B", "RNA: single-stranded, uracil in place of thymine"),
    ("3c", "3.18B", "Protein synthesis: transcription and translation"),
    ("3d", "3.19", "Alleles and how they cause variation"),
    ("3d", "3.20", "Dominant, recessive, homozygous, heterozygous, phenotype, genotype"),
    ("3d", "3.21B", "Codominance"),
    ("3d", "3.22", "Polygenic inheritance"),
    ("3d", "3.23", "Monohybrid crosses with a genetic diagram"),
    ("3d", "3.24", "Reading a family pedigree"),
    ("3d", "3.25", "Predicting probabilities from a cross"),
    ("3d", "3.26", "Sex determination by the X and Y chromosomes"),
    ("3d", "3.27", "Sex of offspring shown with a genetic diagram"),
    ("3e", "3.28", "Mitosis: two genetically identical diploid cells"),
    ("3e", "3.29", "Where mitosis happens: growth, repair, cloning, asexual reproduction"),
    ("3e", "3.30", "Meiosis: four haploid, genetically different cells"),
    ("3e", "3.31", "Random fertilisation and variation"),
    ("3e", "3.32", "Human diploid and haploid numbers"),
    ("3f", "3.33", "Genetic, environmental and combined variation"),
    ("3f", "3.34", "Mutation as a rare random change"),
    ("3f", "3.35B", "How a DNA change alters the phenotype through the protein"),
    ("3f", "3.36B", "Why most mutations have no effect"),
    ("3f", "3.37B", "What raises the mutation rate"),
    ("3f", "3.38", "Darwin's theory of natural selection"),
    ("3f", "3.39", "Antibiotic resistance as natural selection"),
    // 4 Ecology and the environment
    ("4a", "4.1", "Population, community, habitat, ecosystem"),
    ("4a", "4.2", "Practical: population size with quadrats"),
    ("4a", "4.3B", "Biodiversity"),
    ("4a", "4.4B", "Practical: distribution along a transect"),
    ("4a", "4.5", "Abiotic and biotic factors and population size"),
    ("4b", "4.6", "Trophic levels named"),
    ("4b", "4.7", "Food chains, food webs and pyramids"),
    ("4b", "4.8", "Transfer of substances and energy along a chain"),
    ("4b", "4.9", "Why only about 10% passes to the next level"),
    ("4c", "4.10", "The carbon cycle"),
    ("4c", "4.11B", "The nitrogen cycle and its bacteria"),
    ("4d", "4.12", "Air pollution: sulfur dioxide and carbon monoxide"),
    ("4d", "4.13", "The greenhouse gases"),
    ("4d", "4.14", "How human activity adds greenhouse gases"),
    ("4d", "4.15", "The enhanced greenhouse effect and global warming"),
    ("4d", "4.16", "Water pollution by sewage"),
    ("4d", "4.17", "Eutrophication"),
    ("4d", "4.18B", "The effects of deforestation"),
    // 5 Use of biological resources
    ("5a", "5.1", "Glasshouses and polythene tunnels"),
    ("5a", "5.2", "Carbon dioxide and temperature and crop yield"),
    ("5a", "5.3", "Fertiliser and crop yield"),
    ("5a", "5.4", "Pest control: biological and chemical, for and against"),
    ("5b", "5.5", "Yeast in bread-making"),
    ("5b", "5.6", "Practical: anaerobic respiration by yeast"),
    ("5b", "5.7", "Lactobacillus in yoghurt"),
    ("5b", "5.8", "The industrial fermenter and its conditions"),
    ("5b", "5.9B", "Fish farming"),
    ("5c", "5.10", "Selective breeding in plants"),
    ("5c", "5.11", "Selective breeding in animals"),
    ("5d", "5.12", "Restriction enzymes and ligase"),
    ("5d", "5.13", "Plasmids and viruses as vectors"),
    ("5d", "5.14", "Manufacturing human insulin with modified bacteria"),
    ("5d", "5.15", "Genetically modified plants and food production"),
    ("5d", "5.16", "Transgenic organisms"),
    ("5e", "5.17B", "Micropropagation from explants"),
    ("5e", "5.18B", "Micropropagation for commercial plant production"),
    ("5e", "5.19B", "Producing cloned mammals"),
    ("5e", "5.20B", "Cloned transgenic animals and human proteins"),
];

/// Chemistry 4CH1. A `C` suffix marks separate-science-only content.
pub const CHEM: &[(&str, &str, &str)] = &[
    // 1 Principles of chemistry
    ("1a", "1.1", "The three states in terms of particle arrangement, movement and energy"),
    ("1a", "1.2", "Changes of state in particle terms"),
    ("1a", "1.3", "Dilution and diffusion experiments as evidence for particles"),
    ("1b", "1.4", "Solvent, solute, solution and saturated solution"),
    ("1b", "1.5C", "Solubility in g per 100 g of solvent"),
    ("1b", "1.6C", "Plotting and reading solubility curves"),
    ("1b", "1.7C", "Practical: solubility of a solid at a given temperature"),
    ("1c", "1.8", "Element, compound or mixture"),
    ("1c", "1.9", "Pure substances have sharp melting and boiling points"),
    ("1c", "1.10", "Separation techniques: filtration, crystallisation, distillation, chromatography"),
    ("1c", "1.11", "Reading a chromatogram"),
    ("1c", "1.12", "Rf values"),
    ("1c", "1.13", "Practical: paper chromatography"),
    ("1d", "1.14", "Atom and molecule"),
    ("1d", "1.15", "Protons, neutrons and electrons: position, mass, charge"),
    ("1d", "1.16", "Atomic number, mass number, isotopes, relative atomic mass"),
    ("1d", "1.17", "Calculating relative atomic mass from isotope abundances"),
    ("1d", "1.18", "How the Periodic Table is arranged"),
    ("1d", "1.19", "Electronic configurations of the first 20 elements"),
    ("1d", "1.20", "Metals and non-metals by conductivity and the character of their oxides"),
    ("1d", "1.21", "Metal or non-metal from position in the table"),
    ("1d", "1.22", "Electronic configuration and group number"),
    ("1d", "1.23", "Why a group reacts similarly"),
    ("1d", "1.24", "Why the noble gases are unreactive"),
    ("1e", "1.25", "Word and balanced symbol equations with state symbols"),
    ("1e", "1.26", "Relative formula mass"),
    ("1f", "1.27", "The mole"),
    ("1f", "1.28", "Mass, moles and relative formula mass"),
    ("1f", "1.29", "Reacting masses from an equation"),
    ("1f", "1.30", "Percentage yield"),
    ("1f", "1.34C", "Calculations with concentration and moles"),
    ("1f", "1.35C", "Gas volumes and the molar volume"),
    ("1g", "1.31", "Finding a formula by experiment"),
    ("1g", "1.32", "Empirical and molecular formula defined"),
    ("1g", "1.33", "Empirical and molecular formula from data"),
    ("1g", "1.36", "Practical: formula of a metal oxide"),
    ("1h", "1.37", "How ions form"),
    ("1h", "1.38", "The charges on the common ions"),
    ("1h", "1.39", "Formulae from ions"),
    ("1h", "1.40", "Dot-and-cross diagrams for ionic compounds"),
    ("1h", "1.41", "Ionic bonding as electrostatic attraction"),
    ("1h", "1.42", "Why giant ionic lattices have high melting points"),
    ("1h", "1.43", "When ionic compounds conduct"),
    ("1i", "1.44", "A covalent bond as a shared pair"),
    ("1i", "1.45", "Covalent bonds as electrostatic attraction"),
    ("1i", "1.46", "Dot-and-cross diagrams for simple molecules"),
    ("1i", "1.47", "Why simple molecular substances are gases, liquids or low-melting solids"),
    ("1i", "1.48", "Boiling point trend with molecule size"),
    ("1i", "1.51", "Covalent compounds do not usually conduct"),
    ("1j", "1.49", "Why giant covalent structures melt at high temperatures"),
    ("1j", "1.50", "Diamond, graphite and C60: structure and properties"),
    ("1k", "1.52C", "Drawing a metallic lattice"),
    ("1k", "1.53C", "Metallic bonding as electrostatic attraction"),
    ("1k", "1.54C", "Conductivity and malleability from the structure"),
    ("1l", "1.55C", "Why covalent compounds do not conduct"),
    ("1l", "1.56C", "Why ionic compounds conduct only when molten or dissolved"),
    ("1l", "1.57C", "Anion and cation"),
    ("1l", "1.58C", "Electrolysis experiments with inert electrodes"),
    ("1l", "1.59C", "Ionic half-equations at each electrode"),
    ("1l", "1.60C", "Practical: electrolysis of aqueous solutions"),
    // 2 Inorganic chemistry
    ("2a", "2.1", "Group 1 with water: similarities and what they show"),
    ("2a", "2.2", "Group 1 with air and water: differences and the trend"),
    ("2a", "2.3", "Predicting other alkali metals"),
    ("2a", "2.4C", "The Group 1 trend explained by electronic configuration"),
    ("2b", "2.5", "The halogens: colours, states and trends"),
    ("2b", "2.6", "Predicting other halogens"),
    ("2b", "2.7", "Displacement reactions and the reactivity trend"),
    ("2b", "2.8C", "The Group 7 trend explained by electronic configuration"),
    ("2c", "2.9", "The composition of dry air"),
    ("2c", "2.10", "Measuring the oxygen in air by reaction"),
    ("2c", "2.11", "Combustion of magnesium, hydrogen and sulfur"),
    ("2c", "2.12", "Carbon dioxide from decomposing carbonates"),
    ("2c", "2.13", "Carbon dioxide as a greenhouse gas"),
    ("2c", "2.14", "Practical: the percentage of oxygen in air"),
    ("2d", "2.15", "A reactivity series from reactions with water"),
    ("2d", "2.16", "A reactivity series from reactions with acid"),
    ("2d", "2.17", "The order of reactivity of the named metals"),
    ("2d", "2.18", "Conditions for rusting"),
    ("2d", "2.19", "Preventing rust: barriers, galvanising, sacrificial protection"),
    ("2d", "2.20", "Oxidation, reduction, redox, oxidising and reducing agents"),
    ("2d", "2.21", "Practical: acids with metals and metal oxides"),
    ("2e", "2.22C", "Metals come from ores"),
    ("2e", "2.23C", "Extraction method and position in the series"),
    ("2e", "2.24C", "Commenting on an extraction process"),
    ("2e", "2.25C", "Uses of aluminium, copper, iron and steel"),
    ("2e", "2.26C", "What an alloy is"),
    ("2e", "2.27C", "Why alloys are harder"),
    ("2f", "2.28", "Litmus, phenolphthalein and methyl orange"),
    ("2f", "2.29", "The pH scale"),
    ("2f", "2.30", "Universal indicator"),
    ("2f", "2.31", "Acids give hydrogen ions, alkalis give hydroxide ions"),
    ("2f", "2.32", "Alkalis neutralise acids"),
    ("2f", "2.33C", "Carrying out a titration"),
    ("2f", "2.35", "Acids and bases as proton transfer"),
    ("2f", "2.36", "Proton donor and proton acceptor"),
    ("2g", "2.34", "Solubility rules for ionic compounds"),
    ("2g", "2.37", "Acids with metals, oxides, hydroxides and carbonates"),
    ("2g", "2.38", "Oxides, hydroxides and ammonia as bases; salts formed"),
    ("2g", "2.39", "Preparing a soluble salt from an insoluble base"),
    ("2g", "2.40C", "Preparing a soluble salt by titration"),
    ("2g", "2.41C", "Preparing an insoluble salt by precipitation"),
    ("2g", "2.42", "Practical: hydrated copper(II) sulfate crystals"),
    ("2g", "2.43C", "Practical: lead(II) sulfate"),
    ("2h", "2.44", "Tests for hydrogen, oxygen, carbon dioxide, ammonia, chlorine"),
    ("2h", "2.45", "Carrying out a flame test"),
    ("2h", "2.46", "Flame colours of the named cations"),
    ("2h", "2.47", "Tests for the named cations"),
    ("2h", "2.48", "Tests for the named anions"),
    ("2h", "2.49", "The anhydrous copper(II) sulfate test for water"),
    ("2h", "2.50", "A physical test for pure water"),
    // 3 Physical chemistry
    ("3a", "3.1", "Exothermic and endothermic"),
    ("3a", "3.2", "Calorimetry experiments"),
    ("3a", "3.3", "Heat energy change from temperature change"),
    ("3a", "3.4", "Molar enthalpy change from Q"),
    ("3a", "3.5C", "Energy level diagrams"),
    ("3a", "3.6C", "Bond breaking endothermic, bond making exothermic"),
    ("3a", "3.7C", "Enthalpy change from bond energies"),
    ("3a", "3.8", "Practical: temperature changes in reactions"),
    ("3b", "3.9", "Experiments on rate of reaction"),
    ("3b", "3.10", "Effects of surface area, concentration, temperature, catalyst"),
    ("3b", "3.11", "Explaining those effects with particles and collisions"),
    ("3b", "3.12", "What a catalyst is"),
    ("3b", "3.13", "Catalysts and activation energy"),
    ("3b", "3.14C", "Reaction profile diagrams"),
    ("3b", "3.15", "Practical: marble chips and acid"),
    ("3b", "3.16", "Practical: catalysts and hydrogen peroxide"),
    ("3c", "3.17", "Reversible reactions and the symbol"),
    ("3c", "3.18", "Examples: hydrated copper sulfate, ammonium chloride"),
    ("3c", "3.19C", "Dynamic equilibrium in a closed system"),
    ("3c", "3.20C", "The characteristics of dynamic equilibrium"),
    ("3c", "3.21C", "Why a catalyst does not move the equilibrium"),
    ("3c", "3.22C", "Temperature and pressure and the position of equilibrium"),
    // 4 Organic chemistry
    ("4a", "4.1", "What a hydrocarbon is"),
    ("4a", "4.2", "Empirical, molecular, general, structural and displayed formulae"),
    ("4a", "4.3", "Homologous series, functional group, isomerism"),
    ("4a", "4.4", "Naming organic compounds"),
    ("4a", "4.5", "Drawing the isomers of a formula"),
    ("4a", "4.6", "Substitution, addition and combustion reactions"),
    ("4b", "4.7", "Crude oil as a mixture of hydrocarbons"),
    ("4b", "4.8", "Fractional distillation of crude oil"),
    ("4b", "4.9", "The main fractions and their uses"),
    ("4b", "4.10", "Trends in colour, boiling point and viscosity"),
    ("4c", "4.11", "What a fuel is"),
    ("4c", "4.12", "Products of complete and incomplete combustion"),
    ("4c", "4.13", "Why carbon monoxide is poisonous"),
    ("4c", "4.14", "Nitrogen oxides from car engines"),
    ("4c", "4.15", "Sulfur dioxide from fuel impurities"),
    ("4c", "4.16", "Acid rain"),
    ("4d", "4.17", "Cracking long-chain alkanes"),
    ("4d", "4.18", "Why cracking is needed"),
    ("4e", "4.19", "The general formula for alkanes"),
    ("4e", "4.20", "Alkanes as saturated hydrocarbons"),
    ("4e", "4.21", "Drawing alkanes up to five carbons"),
    ("4e", "4.22", "Alkanes with halogens in ultraviolet light"),
    ("4f", "4.23", "The alkene functional group"),
    ("4f", "4.24", "The general formula for alkenes"),
    ("4f", "4.25", "Alkenes as unsaturated hydrocarbons"),
    ("4f", "4.26", "Drawing alkenes up to four carbons"),
    ("4f", "4.27", "Alkenes with bromine"),
    ("4f", "4.28", "Bromine water to tell alkanes from alkenes"),
    ("4g", "4.29C", "The alcohol functional group"),
    ("4g", "4.30C", "Drawing the first four alcohols"),
    ("4g", "4.31C", "Oxidising ethanol"),
    ("4g", "4.32C", "Making ethanol: fermentation and hydration"),
    ("4g", "4.33C", "Why fermentation needs those conditions"),
    ("4h", "4.34C", "The carboxylic acid functional group"),
    ("4h", "4.35C", "Drawing the first four carboxylic acids"),
    ("4h", "4.36C", "Carboxylic acids with metals and carbonates"),
    ("4h", "4.37C", "Vinegar as ethanoic acid"),
    ("4h", "4.38C", "The ester functional group"),
    ("4h", "4.39C", "Ethyl ethanoate from ethanol and ethanoic acid"),
    ("4h", "4.40C", "Drawing ethyl ethanoate"),
    ("4h", "4.41C", "Drawing an ester from its acid and alcohol"),
    ("4h", "4.42C", "Esters: volatile, scented, used in flavourings"),
    ("4h", "4.43C", "Practical: preparing an ester"),
    ("4i", "4.44", "Addition polymers from monomers"),
    ("4i", "4.45", "Drawing the repeat unit"),
    ("4i", "4.46", "Monomer from repeat unit"),
    ("4i", "4.47", "Disposal problems of addition polymers"),
    ("4i", "4.48C", "Condensation polymerisation"),
    ("4i", "4.49C", "Drawing a polyester"),
    ("4i", "4.50C", "Biodegradable polyesters"),
];

/// Physics 4PH1. A `P` suffix marks separate-science-only content. Note the
/// count: 195, not the 191 a first-line grep of the PDF gives - four
/// statements (1.8, 3.20, 4.7, 4.10) have their number and their text on
/// different lines because a formula sits between them.
pub const PHYS: &[(&str, &str, &str)] = &[
    // 1 Forces and motion
    ("1a", "1.1", "Units for motion: kg, m, m/s, m/s², N, s, N/kg"),
    ("1a", "1.2P", "Units for moments and momentum: N m, kg m/s"),
    ("1a", "1.3", "Distance-time graphs"),
    ("1a", "1.5", "Practical: the motion of everyday objects"),
    ("1a", "1.7", "Velocity-time graphs"),
    ("1a", "1.8", "Acceleration from the gradient of a velocity-time graph"),
    ("1a", "1.9", "Distance from the area under a velocity-time graph"),
    ("1b", "1.4", "Average speed, distance and time"),
    ("1b", "1.6", "Acceleration, change in velocity and time"),
    ("1b", "1.10", "v² = u² + 2as"),
    ("1c", "1.11", "What forces do: change speed, shape or direction"),
    ("1c", "1.12", "Types of force"),
    ("1c", "1.13", "Vectors and scalars"),
    ("1c", "1.14", "Force is a vector"),
    ("1c", "1.15", "Resultant of forces along a line"),
    ("1d", "1.16", "Friction opposes motion"),
    ("1d", "1.17", "F = ma"),
    ("1d", "1.18", "W = mg"),
    ("1e", "1.19", "Stopping distance = thinking + braking"),
    ("1e", "1.20", "What affects stopping distance"),
    ("1e", "1.21", "Forces on a falling object and terminal velocity"),
    ("1f", "1.22", "Practical: extension against force for springs, wires and bands"),
    ("1f", "1.23", "The linear region and Hooke's law"),
    ("1f", "1.24", "Elastic behaviour"),
    ("1g", "1.25P", "Momentum = mass × velocity"),
    ("1g", "1.26P", "Momentum and safety features"),
    ("1g", "1.27P", "Conservation of momentum in collisions"),
    ("1g", "1.28P", "Force = change in momentum ÷ time"),
    ("1g", "1.29P", "Newton's third law"),
    ("1h", "1.30P", "Moment = force × perpendicular distance"),
    ("1h", "1.31P", "Weight acts through the centre of gravity"),
    ("1h", "1.32P", "The principle of moments"),
    ("1h", "1.33P", "Upward forces on a supported beam"),
    // 2 Electricity
    ("2a", "2.1", "Units for electricity: A, C, J, Ω, s, V, W"),
    ("2a", "2.8", "Current in a series circuit depends on voltage and resistance"),
    ("2a", "2.10", "The effect of changing resistance on current"),
    ("2a", "2.13", "V = IR"),
    ("2b", "2.7", "When series or parallel is the right choice"),
    ("2b", "2.17", "Current is conserved at a junction"),
    ("2b", "2.18", "Voltage across parallel components is the same"),
    ("2b", "2.19", "Currents, voltages and resistances of two components"),
    ("2c", "2.9", "Current-voltage graphs for wires, resistors, lamps and diodes"),
    ("2c", "2.11", "LDRs and thermistors"),
    ("2c", "2.12", "Lamps and LEDs as current indicators"),
    ("2d", "2.2", "Insulation, earthing, fuses and circuit breakers"),
    ("2d", "2.3", "Why a current in a resistor transfers energy and heats it"),
    ("2d", "2.4", "P = IV"),
    ("2d", "2.5", "E = IVt"),
    ("2d", "2.6", "Mains a.c. and battery d.c."),
    ("2e", "2.14", "Current as rate of flow of charge"),
    ("2e", "2.15", "Q = It"),
    ("2e", "2.16", "Current in metals is a flow of electrons"),
    ("2e", "2.20", "Voltage as energy per unit charge; the volt as a joule per coulomb"),
    ("2e", "2.21", "E = QV"),
    ("2f", "2.22P", "Conductors and insulators"),
    ("2f", "2.23P", "Practical: charging insulators by friction"),
    ("2f", "2.24P", "How positive and negative charges arise"),
    ("2f", "2.25P", "Attraction and repulsion between charges"),
    ("2f", "2.26P", "Electrostatic effects explained by electron movement"),
    ("2f", "2.27P", "Dangers of static: fuelling, lightning"),
    ("2f", "2.28P", "Uses of static: photocopiers, inkjet printers"),
    // 3 Waves
    ("3a", "3.1", "Units for waves: °, Hz, m, m/s, s"),
    ("3a", "3.2", "Longitudinal and transverse waves"),
    ("3a", "3.3", "Amplitude, wavefront, frequency, wavelength, period"),
    ("3a", "3.4", "Waves carry energy and information, not matter"),
    ("3a", "3.5", "v = fλ"),
    ("3a", "3.6", "f = 1/T"),
    ("3a", "3.7", "Using the wave equations for sound and light"),
    ("3a", "3.8", "The Doppler effect"),
    ("3a", "3.9", "All waves reflect and refract"),
    ("3b", "3.10", "Light as part of the electromagnetic spectrum"),
    ("3b", "3.11", "The spectrum in order of wavelength and frequency"),
    ("3b", "3.12", "Uses of each part of the spectrum"),
    ("3b", "3.13", "Harmful effects of over-exposure"),
    ("3c", "3.14", "Light is transverse and can be reflected and refracted"),
    ("3c", "3.15", "The law of reflection"),
    ("3c", "3.16", "Ray diagrams for reflection and refraction"),
    ("3c", "3.17", "Practical: refraction through blocks and prisms"),
    ("3d", "3.18", "n = sin i / sin r"),
    ("3d", "3.19", "Practical: refractive index of glass"),
    ("3d", "3.20", "Total internal reflection in optical fibres and prisms"),
    ("3d", "3.21", "The critical angle"),
    ("3d", "3.22", "sin c = 1/n"),
    ("3e", "3.23", "Sound as a longitudinal wave that reflects and refracts"),
    ("3e", "3.24P", "Human hearing: 20 Hz to 20 kHz"),
    ("3e", "3.25P", "Practical: the speed of sound in air"),
    ("3e", "3.26P", "Oscilloscope and microphone to display a sound"),
    ("3e", "3.27P", "Practical: frequency from an oscilloscope trace"),
    ("3e", "3.28P", "Pitch and frequency"),
    ("3e", "3.29P", "Loudness and amplitude"),
    // 4 Energy resources and energy transfers
    ("4a", "4.1", "Units for energy: kg, J, m, m/s, N, s, W"),
    ("4a", "4.2", "Energy stores and transfers"),
    ("4a", "4.3", "Conservation of energy"),
    ("4b", "4.4", "Efficiency = useful output ÷ total output"),
    ("4b", "4.5", "Devices and situations, including Sankey diagrams"),
    ("4c", "4.6", "Conduction, convection and radiation"),
    ("4c", "4.7", "Convection in everyday situations"),
    ("4c", "4.8", "Emission and absorption of radiation: surface and temperature"),
    ("4c", "4.9", "Practical: thermal energy transfer"),
    ("4c", "4.10", "Reducing unwanted transfer: insulation"),
    ("4d", "4.11", "Work = force × distance"),
    ("4d", "4.12", "Work done equals energy transferred"),
    ("4d", "4.13", "GPE = mgh"),
    ("4d", "4.14", "KE = ½mv²"),
    ("4d", "4.15", "GPE and KE linked by conservation of energy"),
    ("4d", "4.16", "Power as rate of energy transfer"),
    ("4d", "4.17", "P = W/t"),
    ("4e", "4.18P", "Energy transfers in generating electricity from each resource"),
    ("4e", "4.19P", "Large-scale generation: for and against"),
    // 5 Solids, liquids and gases
    ("5a", "5.1", "Units for this section: °C, K, J, kg, kg/m³, m, m², m³, m/s², N, Pa"),
    ("5a", "5.3", "Density = mass ÷ volume"),
    ("5a", "5.4", "Practical: measuring density"),
    ("5a", "5.5", "Pressure = force ÷ area"),
    ("5a", "5.6", "Pressure in a fluid acts equally in all directions"),
    ("5a", "5.7", "Pressure difference = height × density × g"),
    ("5b", "5.2P", "The unit J/kg °C"),
    ("5b", "5.8P", "Heating changes the energy stored and temperature or state"),
    ("5b", "5.9P", "Melting and boiling in particle terms"),
    ("5b", "5.10P", "Particle arrangement and motion in solids, liquids and gases"),
    ("5b", "5.11P", "Practical: a temperature-time graph showing constant temperature during a change of state"),
    ("5b", "5.12P", "Specific heat capacity defined"),
    ("5b", "5.13P", "Q = mcΔT"),
    ("5b", "5.14P", "Practical: specific heat capacity of water and solids"),
    ("5c", "5.15", "Gas molecules move randomly and exert a force on the walls"),
    ("5c", "5.16", "Why there is an absolute zero"),
    ("5c", "5.17", "The Kelvin scale and conversion"),
    ("5c", "5.18", "Temperature and average molecular kinetic energy"),
    ("5c", "5.19", "Kelvin temperature proportional to average kinetic energy"),
    ("5d", "5.20", "Pressure, volume and temperature qualitatively"),
    ("5d", "5.21", "p₁/T₁ = p₂/T₂"),
    ("5d", "5.22", "p₁V₁ = p₂V₂"),
    // 6 Magnetism and electromagnetism
    ("6a", "6.1", "Units: A, V, W"),
    ("6a", "6.2", "Magnets attract and repel"),
    ("6a", "6.3", "Magnetically hard and soft materials"),
    ("6a", "6.4", "Magnetic field lines"),
    ("6a", "6.5", "Induced magnetism"),
    ("6a", "6.6", "Practical: field patterns of a bar magnet and between magnets"),
    ("6a", "6.7", "A uniform field between two magnets"),
    ("6a", "6.8", "A current produces a magnetic field"),
    ("6a", "6.9P", "Building an electromagnet"),
    ("6a", "6.10P", "Field patterns for a wire, a flat coil and a solenoid"),
    ("6b", "6.11P", "Force on a moving charge in a field"),
    ("6b", "6.12", "Why a current-carrying wire in a field feels a force; the motor"),
    ("6b", "6.13", "The left-hand rule"),
    ("6b", "6.14", "What changes the size of the force"),
    ("6c", "6.15", "Induced voltage when a conductor moves through a field"),
    ("6c", "6.16", "Generating electricity with a rotating magnet in a coil"),
    ("6d", "6.17P", "Transformer structure and why it needs a.c."),
    ("6d", "6.18P", "Step-up and step-down transformers in the grid"),
    ("6d", "6.19P", "Vp/Vs = Np/Ns"),
    ("6d", "6.20P", "VpIp = VsIs for a 100% efficient transformer"),
    // 7 Radioactivity and particles
    ("7a", "7.1", "Units: Bq, cm, h, min, s"),
    ("7a", "7.2", "Atomic structure and nuclide notation"),
    ("7a", "7.3", "Proton number, nucleon number, isotope"),
    ("7a", "7.4", "Alpha, beta and gamma are ionising radiations from unstable nuclei"),
    ("7a", "7.5", "Nature and penetrating power of each radiation"),
    ("7a", "7.6", "Practical: penetrating powers"),
    ("7b", "7.7", "How emission changes atomic and mass numbers"),
    ("7b", "7.8", "Balancing nuclear equations"),
    ("7c", "7.9", "Detecting radiation: film and Geiger-Müller tube"),
    ("7c", "7.10", "Sources of background radiation"),
    ("7c", "7.11", "Activity falls over time, measured in becquerels"),
    ("7c", "7.12", "Half-life defined"),
    ("7c", "7.13", "Half-life calculations"),
    ("7d", "7.14", "Uses in industry and medicine"),
    ("7d", "7.15", "Contamination and irradiation"),
    ("7d", "7.16", "Dangers of ionising radiation and how they are managed"),
    ("7e", "7.17", "Nuclear reactions as an energy source"),
    ("7e", "7.18", "Fission of U-235 by neutron collision"),
    ("7e", "7.19", "Fission products: daughter nuclei and neutrons"),
    ("7e", "7.20", "The chain reaction"),
    ("7e", "7.21", "Control rods and the moderator"),
    ("7e", "7.22", "Shielding a reactor"),
    ("7f", "7.23", "Fusion and fission compared"),
    ("7f", "7.24", "Fusion creates larger nuclei and loses mass"),
    ("7f", "7.25", "Fusion powers stars"),
    ("7f", "7.26", "Why fusion needs high temperature and pressure"),
    // 8 Astrophysics
    ("8a", "8.1", "Units for astrophysics"),
    ("8a", "8.2", "Universe, galaxy, solar system, Milky Way"),
    ("8a", "8.3", "Why g varies between bodies"),
    ("8a", "8.4", "Gravity keeps moons, planets, satellites and comets in orbit"),
    ("8a", "8.5", "Orbits of comets, moons and planets compared"),
    ("8a", "8.6", "Orbital speed = 2πr / T"),
    ("8b", "8.7", "Classifying stars by colour"),
    ("8b", "8.8", "Colour and surface temperature"),
    ("8b", "8.9", "The life of a Sun-like star"),
    ("8b", "8.10", "The life of a more massive star"),
    ("8c", "8.11P", "Absolute magnitude"),
    ("8c", "8.12P", "The Hertzsprung-Russell diagram"),
    ("8c", "8.13P", "The past evolution of the universe and the Big Bang"),
    ("8c", "8.14P", "Evidence for the Big Bang"),
    ("8c", "8.15P", "Doppler shift from a moving source"),
    ("8c", "8.16P", "The red-shift equation"),
    ("8c", "8.17P", "Red-shift and the distance of galaxies"),
    ("8c", "8.18P", "Red-shift as evidence for expansion"),
];


/// Economics - Cambridge IGCSE (9-1) 0987, syllabus for 2027-2029. Cambridge
/// numbers each sub-point section.subsection.n, and every sub-point belongs to
/// the topic with the same subsection code, so the mapping is exact.
pub const ECON: &[(&str, &str, &str)] = &[
    // 1 The basic economic problem
    ("1.1", "1.1.1", "Finite resources against infinite wants; scarcity for each decision-maker"),
    ("1.1", "1.1.2", "What, how and for whom to produce"),
    ("1.1", "1.1.3", "Economic goods and free goods"),
    ("1.2", "1.2.1", "The four factors and their rewards"),
    ("1.2", "1.2.2", "What changes the quantity and quality of each factor"),
    ("1.3", "1.3.1", "Opportunity cost defined, with examples"),
    ("1.3", "1.3.2", "Opportunity cost in the decisions of consumers, workers, firms and governments"),
    ("1.4", "1.4.1", "Drawing and reading a PPC"),
    ("1.4", "1.4.2", "Points inside, on and beyond the curve"),
    ("1.4", "1.4.3", "Movements along the curve as opportunity cost"),
    ("1.4", "1.4.4", "Shifts of the curve and economic growth"),
    // 2 The allocation of resources
    ("2.1", "2.1.1", "What a market is, examples, buyers and sellers"),
    ("2.2", "2.2.1", "Individual and market demand; the demand diagram"),
    ("2.2", "2.2.2", "Extensions and contractions of demand"),
    ("2.2", "2.2.3", "Increases and decreases in demand"),
    ("2.3", "2.3.1", "Individual and market supply; the supply diagram"),
    ("2.3", "2.3.2", "Extensions and contractions of supply"),
    ("2.3", "2.3.3", "Increases and decreases in supply"),
    ("2.4", "2.4.1", "The price mechanism answering the three questions"),
    ("2.4", "2.4.2", "Equilibrium from a schedule and from a diagram"),
    ("2.4", "2.4.3", "Disequilibrium: shortages and surpluses"),
    ("2.5", "2.5.1", "How demand and supply changes move price"),
    ("2.5", "2.5.2", "The effect of a price change on sales, with diagrams"),
    ("2.6", "2.6.1", "PED defined"),
    ("2.6", "2.6.2", "Calculating PED and reading the value, with diagrams"),
    ("2.6", "2.6.3", "What makes demand elastic or inelastic"),
    ("2.6", "2.6.4", "PED, consumer spending and firms' revenue"),
    ("2.6", "2.6.5", "Why PED matters to each decision-maker"),
    ("2.7", "2.7.1", "PES defined"),
    ("2.7", "2.7.2", "Calculating PES and reading the value, with diagrams"),
    ("2.7", "2.7.3", "What makes supply elastic or inelastic"),
    ("2.8", "2.8.1", "The market economic system defined"),
    ("2.8", "2.8.2", "The market system: for and against"),
    ("2.9", "2.9.1", "Market failure defined"),
    ("2.9", "2.9.2", "Public, merit and demerit goods; private, external and social costs and benefits; monopoly"),
    ("2.9", "2.9.3", "Causes of market failure"),
    ("2.9", "2.9.4", "Consequences of market failure"),
    ("2.10", "2.10.1", "The mixed economic system defined"),
    ("2.10", "2.10.2", "The mixed system: for and against"),
    ("2.10", "2.10.3", "Intervention: price controls, taxes, subsidies, regulation, ownership, provision, quotas"),
    // 3 Microeconomic decision-makers
    ("3.1", "3.1.1", "Money: forms, functions, characteristics"),
    ("3.1", "3.1.2", "Central and commercial banks"),
    ("3.2", "3.2.1", "What shapes household spending, saving and borrowing"),
    ("3.3", "3.3.1", "Choosing an occupation: wage and non-wage factors"),
    ("3.3", "3.3.2", "How wages are set: labour demand and supply, unions, minimum wage, with diagrams"),
    ("3.3", "3.3.3", "Why wages differ"),
    ("3.3", "3.3.4", "Occupational and geographical mobility of labour"),
    ("3.3", "3.3.5", "Division of labour"),
    ("3.4", "3.4.1", "Types of firm: sector, ownership, size"),
    ("3.4", "3.4.2", "Horizontal, vertical and conglomerate mergers"),
    ("3.4", "3.4.3", "Economies and diseconomies of scale, with the ATC diagram"),
    ("3.5", "3.5.1", "What drives a firm's demand for factors"),
    ("3.5", "3.5.2", "Labour-intensive and capital-intensive production"),
    ("3.5", "3.5.3", "Production against productivity; the effect of investment"),
    ("3.6", "3.6.1", "TC, ATC, FC, AFC, VC, AVC defined"),
    ("3.6", "3.6.2", "Calculating the six costs; cost diagrams"),
    ("3.6", "3.6.3", "Total and average revenue defined"),
    ("3.6", "3.6.4", "Calculating revenue; sales and revenue"),
    ("3.6", "3.6.5", "Objectives of firms"),
    ("3.7", "3.7.1", "Competitive markets and their effects"),
    ("3.7", "3.7.2", "Monopoly and its effects"),
    // 4 Government and the macroeconomy
    ("4.1", "4.1.1", "The six macroeconomic aims, their criteria and their conflicts"),
    ("4.2", "4.2.1", "The budget; deficits and surpluses, and their size"),
    ("4.2", "4.2.2", "Why governments spend, and the effects"),
    ("4.2", "4.2.3", "Why governments tax; tax classifications; who taxes affect"),
    ("4.2", "4.2.4", "Fiscal policy defined"),
    ("4.2", "4.2.5", "Fiscal measures: taxes and spending"),
    ("4.2", "4.2.6", "How fiscal policy serves the aims"),
    ("4.3", "4.3.1", "Money supply and monetary policy defined"),
    ("4.3", "4.3.2", "Monetary measures: interest rate, money supply, exchange rate"),
    ("4.3", "4.3.3", "How monetary policy serves the aims"),
    ("4.4", "4.4.1", "Supply-side policy defined"),
    ("4.4", "4.4.2", "Supply-side measures"),
    ("4.4", "4.4.3", "How supply-side policy serves the aims"),
    ("4.5", "4.5.1", "Economic growth defined"),
    ("4.5", "4.5.2", "Real GDP as the measure"),
    ("4.5", "4.5.3", "Causes and consequences of growth"),
    ("4.5", "4.5.4", "Recession: definition, causes, consequences"),
    ("4.5", "4.5.5", "Policies for growth and how well they work"),
    ("4.6", "4.6.1", "Employment, unemployment, full employment defined"),
    ("4.6", "4.6.2", "The labour force survey and the unemployment rate"),
    ("4.6", "4.6.3", "Frictional, structural, cyclical, seasonal"),
    ("4.6", "4.6.4", "Consequences of unemployment"),
    ("4.6", "4.6.5", "Policies against unemployment and how well they work"),
    ("4.7", "4.7.1", "Inflation and deflation defined"),
    ("4.7", "4.7.2", "The CPI"),
    ("4.7", "4.7.3", "Demand-pull and cost-push"),
    ("4.7", "4.7.4", "Consequences of inflation, including for savers, lenders and borrowers"),
    ("4.7", "4.7.5", "Policies against inflation and how well they work"),
    // 5 Economic development
    ("5.1", "5.1.1", "Real GDP per head and the HDI as indicators"),
    ("5.1", "5.1.2", "Why living standards and income distribution differ"),
    ("5.2", "5.2.1", "Absolute and relative poverty"),
    ("5.2", "5.2.2", "Causes of poverty"),
    ("5.2", "5.2.3", "Policies against poverty and for redistribution"),
    ("5.3", "5.3.1", "Birth rate, death rate, migration, and why they vary"),
    ("5.3", "5.3.2", "Optimum population; effects of changing size and structure"),
    ("5.4", "5.4.1", "Why countries differ in development, and what follows"),
    // 6 International trade and globalisation
    ("6.1", "6.1.1", "Specialisation by country: basis, for and against"),
    ("6.1", "6.1.2", "Free trade: definition, for and against"),
    ("6.2", "6.2.1", "Globalisation defined"),
    ("6.2", "6.2.2", "Causes and effects of changes in globalisation"),
    ("6.2", "6.2.3", "Multinationals: host and home countries"),
    ("6.2", "6.2.4", "Tariffs, quotas, subsidies, embargoes"),
    ("6.2", "6.2.5", "Reasons for protection"),
    ("6.2", "6.2.6", "Consequences of protection"),
    ("6.3", "6.3.1", "The exchange rate defined"),
    ("6.3", "6.3.2", "Why currencies are bought and sold"),
    ("6.3", "6.3.3", "How the rate is set; floating rates, appreciation, depreciation, fluctuations"),
    ("6.3", "6.3.4", "Effects of a change on exports and imports"),
    ("6.4", "6.4.1", "The four components of the current account, and calculating balances"),
    ("6.4", "6.4.2", "Causes of deficits and surpluses"),
    ("6.4", "6.4.3", "Consequences for GDP, employment, inflation, the exchange rate"),
    ("6.4", "6.4.4", "Policies for balance of payments stability"),
];

/// Business - AQA GCSE 8132. AQA numbers its subsections (3.1.1 ...) but not
/// the outcomes inside them, so unlike Maths, the sciences and Economics there
/// is no board numbering to check this table against. The letters here are
/// ours, assigned in the order the outcomes appear in the specification, and
/// the count was made by reading the document, not by machine. A test still
/// checks every entry lands on a real topic and that no letter is skipped.
pub const BUS: &[(&str, &str, &str)] = &[
    // 3.1 Business in the real world
    ("3.1.1", "3.1.1a", "What a business is and the reasons for starting one"),
    ("3.1.1", "3.1.1b", "Goods and services; needs and wants"),
    ("3.1.1", "3.1.1c", "The four factors of production"),
    ("3.1.1", "3.1.1d", "Opportunity cost"),
    ("3.1.1", "3.1.1e", "The three sectors, with examples"),
    ("3.1.1", "3.1.1f", "Enterprise and the entrepreneur"),
    ("3.1.1", "3.1.1g", "What entrepreneurs are like"),
    ("3.1.1", "3.1.1h", "Why entrepreneurs start businesses"),
    ("3.1.1", "3.1.1i", "The constantly changing business environment"),
    ("3.1.2", "3.1.2a", "The legal structures a business can adopt"),
    ("3.1.2", "3.1.2b", "Benefits and drawbacks of each structure"),
    ("3.1.2", "3.1.2c", "Limited liability and who has it"),
    ("3.1.2", "3.1.2d", "Choosing a structure for a start-up or an established business"),
    ("3.1.3", "3.1.3a", "The main aims and objectives"),
    ("3.1.3", "3.1.3b", "What objectives are for"),
    ("3.1.3", "3.1.3c", "Why objectives differ between businesses"),
    ("3.1.3", "3.1.3d", "Why objectives change as a business grows"),
    ("3.1.3", "3.1.3e", "Success measured by more than profit"),
    ("3.1.4", "3.1.4a", "What a stakeholder is and the main ones"),
    ("3.1.4", "3.1.4b", "What each stakeholder wants"),
    ("3.1.4", "3.1.4c", "How stakeholders influence a business, and where they conflict"),
    ("3.1.5", "3.1.5a", "The factors behind a location decision"),
    ("3.1.6", "3.1.6a", "Why businesses plan"),
    ("3.1.6", "3.1.6b", "The sections of a business plan"),
    ("3.1.6", "3.1.6c", "Benefits and drawbacks of planning"),
    ("3.1.6", "3.1.6d", "Variable, fixed and total costs"),
    ("3.1.6", "3.1.6e", "Revenue, costs, profit and loss"),
    ("3.1.7", "3.1.7a", "Advantages and disadvantages of growth"),
    ("3.1.7", "3.1.7b", "Organic and external methods of expansion"),
    ("3.1.7", "3.1.7c", "Economies of scale as the benefit of growth; diseconomies as the drawback"),
    ("3.1.7", "3.1.7d", "Purchasing and technical economies"),
    ("3.1.7", "3.1.7e", "Why diseconomies set in"),
    ("3.1.7", "3.1.7f", "Calculating and interpreting average unit cost"),
    // 3.2 Influences on business
    ("3.2.1", "3.2.1a", "E-commerce and access to wider markets"),
    ("3.2.1", "3.2.1b", "Digital communication with stakeholders, with real examples"),
    ("3.2.2", "3.2.2a", "Ethical behaviour, examples, benefits and drawbacks"),
    ("3.2.2", "3.2.2b", "The trade-off between ethics and profit"),
    ("3.2.2", "3.2.2c", "Environmental responsibility: congestion, recycling, waste, pollution"),
    ("3.2.2", "3.2.2d", "Global warming and scarce resources; sustainability against profit"),
    ("3.2.3", "3.2.3a", "Interest rates and businesses that borrow"),
    ("3.2.3", "3.2.3b", "Interest rates and consumer and business spending"),
    ("3.2.3", "3.2.3c", "The level of employment"),
    ("3.2.3", "3.2.3d", "Consumer spending as incomes change"),
    ("3.2.4", "3.2.4a", "Globalisation: benefits and drawbacks for UK businesses"),
    ("3.2.4", "3.2.4b", "Competing internationally on design, quality and price"),
    ("3.2.4", "3.2.4c", "Exchange rates and the profit and sales of importers and exporters"),
    ("3.2.5", "3.2.5a", "Employment law: minimum and living wage, the Equality Act"),
    ("3.2.5", "3.2.5b", "Health and safety law, and the benefits of a safe workplace"),
    ("3.2.5", "3.2.5c", "Consumer law, including trade descriptions"),
    ("3.2.5", "3.2.5d", "The effects of legislation on a business and of failing to comply"),
    ("3.2.6", "3.2.6a", "What a market and competition are"),
    ("3.2.6", "3.2.6b", "The impact of competition, and when there is little or none"),
    ("3.2.6", "3.2.6c", "Risk and why every business faces uncertainty"),
    ("3.2.6", "3.2.6d", "Why entrepreneurs take the risk, and how businesses reduce it"),
    // 3.3 Business operations
    ("3.3.1", "3.3.1a", "Job and flow production and when each suits"),
    ("3.3.1", "3.3.1b", "Lean production"),
    ("3.3.1", "3.3.1c", "Just-in-time"),
    ("3.3.2", "3.3.2a", "Just-in-time against just-in-case for a given business"),
    ("3.3.2", "3.3.2b", "The cost of lower stock: more deliveries, lost bulk discounts, against holding buffer stock"),
    ("3.3.2", "3.3.2c", "Choosing a supplier: price, quality, reliability"),
    ("3.3.2", "3.3.2d", "Procurement and logistics and their effect on efficiency and unit cost"),
    ("3.3.2", "3.3.2e", "Effective supply chain management"),
    ("3.3.3", "3.3.3a", "Customer expectations of quality in goods and services"),
    ("3.3.3", "3.3.3b", "Identifying and measuring quality problems, and their consequences"),
    ("3.3.3", "3.3.3c", "Total quality management and its advantages"),
    ("3.3.3", "3.3.3d", "The costs and benefits of maintaining quality, and quality as a business grows"),
    ("3.3.4", "3.3.4a", "The sales process"),
    ("3.3.4", "3.3.4b", "Customer engagement and post-sales service"),
    ("3.3.4", "3.3.4c", "Benefits of good service"),
    ("3.3.4", "3.3.4d", "Dangers of poor service"),
    ("3.3.4", "3.3.4e", "How ICT has changed customer service"),
    // 3.4 Human resources
    ("3.4.1", "3.4.1a", "Span of control, chain of command, delayering, delegation"),
    ("3.4.1", "3.4.1b", "Why businesses have structures; job roles and responsibilities"),
    ("3.4.1", "3.4.1c", "Tall and flat structures and how each is managed"),
    ("3.4.1", "3.4.1d", "Centralisation and decentralisation"),
    ("3.4.1", "3.4.1e", "How structure affects communication"),
    ("3.4.2", "3.4.2a", "Internal and external recruitment"),
    ("3.4.2", "3.4.2b", "The stages of recruitment and selection"),
    ("3.4.2", "3.4.2c", "What effective recruitment gives a business"),
    ("3.4.2", "3.4.2d", "Part-time, full-time, job share and zero-hours contracts"),
    ("3.4.2", "3.4.2e", "Benefits of full- and part-time employment"),
    ("3.4.3", "3.4.3a", "What a motivated workforce gives a business"),
    ("3.4.3", "3.4.3b", "Financial methods: salary, wage, commission, profit sharing"),
    ("3.4.3", "3.4.3c", "Non-financial methods: management style, training, responsibility, fringe benefits"),
    ("3.4.4", "3.4.4a", "Why businesses train"),
    ("3.4.4", "3.4.4b", "Induction, on-the-job and off-the-job training"),
    ("3.4.4", "3.4.4c", "The benefits of induction"),
    ("3.4.4", "3.4.4d", "On-the-job against off-the-job, and which suits a given business"),
    // 3.5 Marketing
    ("3.5.1", "3.5.1a", "Why identifying and satisfying customer needs matters"),
    ("3.5.2", "3.5.2a", "Segmentation by gender, age, location and income, and why businesses use it"),
    ("3.5.3", "3.5.3a", "Why businesses research: demand, competition, target market"),
    ("3.5.3", "3.5.3b", "Primary and secondary methods, and choosing between them"),
    ("3.5.3", "3.5.3c", "Qualitative and quantitative research"),
    ("3.5.3", "3.5.3d", "Using research findings to decide"),
    ("3.5.3", "3.5.3e", "Reading tables and charts; market share"),
    ("3.5.4", "3.5.4a", "Pricing methods: skimming, penetration, competitive, loss leader, cost-plus"),
    ("3.5.4", "3.5.4b", "What influences a pricing decision"),
    ("3.5.4", "3.5.4c", "Price and demand: the basic relationship"),
    ("3.5.4", "3.5.4d", "Benefits and risks of new products; design, image and the target market"),
    ("3.5.4", "3.5.4e", "Differentiation: USP and brand image"),
    ("3.5.4", "3.5.4f", "The product life cycle and extension strategies"),
    ("3.5.4", "3.5.4g", "The product portfolio and the Boston matrix"),
    ("3.5.4", "3.5.4h", "Promotional methods and their benefits and drawbacks"),
    ("3.5.4", "3.5.4i", "What decides the promotional mix, and the reasons for promotion"),
    ("3.5.4", "3.5.4j", "Distribution channels: retailers, telesales"),
    ("3.5.4", "3.5.4k", "E-commerce and m-commerce, and their reach"),
    ("3.5.4", "3.5.4l", "The four elements working together, and how the mix evolves"),
    // 3.6 Finance
    ("3.6.1", "3.6.1a", "Internal and external sources of finance"),
    ("3.6.1", "3.6.1b", "Advantages and disadvantages of each in a given situation"),
    ("3.6.1", "3.6.1c", "Sources for new and for established businesses"),
    ("3.6.2", "3.6.2a", "Consequences of cash-flow problems; the value of positive cash flow"),
    ("3.6.2", "3.6.2b", "How and why forecasts are built"),
    ("3.6.2", "3.6.2c", "Completing and reading parts of a forecast"),
    ("3.6.2", "3.6.2d", "Solutions to cash-flow problems"),
    ("3.6.3", "3.6.3a", "Variable, fixed and total costs; revenue, costs, profit and loss"),
    ("3.6.3", "3.6.3b", "Investment projects and average rate of return"),
    ("3.6.3", "3.6.3c", "Break-even output and reading a break-even chart"),
    ("3.6.3", "3.6.3d", "Break-even point and margin of safety from a chart"),
    ("3.6.3", "3.6.3e", "How useful break-even analysis is"),
    ("3.6.4", "3.6.4a", "Why financial statements matter"),
    ("3.6.4", "3.6.4b", "The parts of an income statement and a statement of financial position"),
    ("3.6.4", "3.6.4c", "Assets and liabilities; the statement as a snapshot"),
    ("3.6.4", "3.6.4d", "Judging performance from an income statement"),
    ("3.6.4", "3.6.4e", "Now, against past years, against competitors, from stakeholders' views"),
    ("3.6.4", "3.6.4f", "Gross and net profit margin"),
];

/// Computer Science 4CP0. Pearson numbers every statement topic.section.n;
/// 89 in all, read from the specification PDF. Six of them sit on the same
/// line as their subsection heading in the PDF, so a line-start count misses
/// them - the count here comes from matching the number anywhere on the line.
pub const CS: &[(&str, &str, &str)] = &[
    // 1 Problem solving
    ("1.1a", "1.1.1", "What an algorithm is and reading one as a flowchart or pseudocode"),
    ("1.1a", "1.1.2", "Writing an algorithm to solve a problem"),
    ("1.1a", "1.1.3", "Working out what a given algorithm does"),
    ("1.1a", "1.1.4", "Determining an algorithm's output for given data"),
    ("1.1a", "1.1.5", "Finding and fixing errors, including with trace tables"),
    ("1.1a", "1.1.6", "Coding an algorithm in a high-level language"),
    ("1.1a", "1.1.7", "How data structures and values shape the choice of algorithm"),
    ("1.1c", "1.1.8", "Bubble sort, merge sort, linear search, binary search"),
    ("1.1a", "1.1.9", "Judging an algorithm's fitness for purpose and efficiency"),
    ("1.2", "1.2.1", "Analysing a problem: inputs, outputs, processing, initialisation"),
    ("1.2", "1.2.2", "Decomposing a problem into sub-problems"),
    ("1.2", "1.2.3", "Abstraction to model the real world"),
    ("1.2", "1.2.4", "Programming abstractions of real-world examples"),
    // 2 Programming
    ("2.1", "2.1.1", "Writing programs in a high-level language"),
    ("2.1", "2.1.2", "Readable code: naming, comments, indentation"),
    ("2.1", "2.1.3", "Logic, syntax and runtime errors"),
    ("2.1", "2.1.4", "Test plans and normal, boundary and erroneous data"),
    ("2.1", "2.1.5", "Reading error messages and fixing errors"),
    ("2.1", "2.1.6", "Tracing a variable's value through a program"),
    ("2.1", "2.1.7", "Strengths and weaknesses of a program, and improvements"),
    ("2.2", "2.2.1", "The structural parts of a program"),
    ("2.2", "2.2.2", "Sequence, selection and iteration"),
    ("2.3", "2.3.1", "Data types: integer, real, Boolean, char, string"),
    ("2.3", "2.3.2", "Data structures: records, one- and two-dimensional arrays"),
    ("2.3", "2.3.3", "Manipulating strings"),
    ("2.3", "2.3.4", "Variables and constants"),
    ("2.3", "2.3.5", "Global and local variables in subprograms"),
    ("2.4", "2.4.1", "Accepting and responding to user input"),
    ("2.4", "2.4.2", "Validation"),
    ("2.4", "2.4.3", "Reading from and writing to a text file"),
    ("2.5", "2.5.1", "Arithmetic operators, including integer division and modulus"),
    ("2.5", "2.5.2", "Relational operators"),
    ("2.5", "2.5.3", "Logic operators AND, OR, NOT"),
    ("2.6", "2.6.1", "Why subprograms help; using built-in and user-written ones"),
    ("2.6", "2.6.2", "Passing data into and out of procedures and functions"),
    ("2.6", "2.6.3", "Subprograms with parameters"),
    // 3 Data
    ("3.1", "3.1.1", "Computers represent everything in binary"),
    ("3.1", "3.1.2", "Unsigned and signed integers, two's complement, and the range a number of bits allows"),
    ("3.1", "3.1.3", "Binary to denary and back, 0 to 255"),
    ("3.1", "3.1.4", "Binary addition, logical and arithmetic shifts, overflow"),
    ("3.1", "3.1.5", "Why hexadecimal is used, and converting hex to binary and denary"),
    ("3.2", "3.2.1", "ASCII and Unicode"),
    ("3.2", "3.2.2", "Bitmaps: pixels, resolution, colour depth"),
    ("3.2", "3.2.3", "Sound as an analogue signal sampled into binary"),
    ("3.2", "3.2.4", "The limits of binary representation: sample rate and resolution"),
    ("3.3", "3.3.1", "Binary and denary multiples: kibibyte, kilobyte and so on"),
    ("3.3", "3.3.2", "Why compress, lossy against lossless, and the trade-offs"),
    ("3.3", "3.3.3", "Run-length encoding"),
    ("3.3", "3.3.4", "File sizes in bytes, and calculating them"),
    ("3.4", "3.4.1", "Why data is encrypted"),
    ("3.4", "3.4.2", "How the Pigpen, Caesar, Vigenere and Rail Fence ciphers work"),
    // 4 Computers
    ("4.1", "4.1.1", "The input-process-output model"),
    ("4.1", "4.1.2", "Sequential, parallel and multi-agent computational models"),
    ("4.2", "4.2.1", "The hardware components and what each does"),
    ("4.2", "4.2.2", "RAM, ROM, cache, virtual memory and flash"),
    ("4.2", "4.2.3", "The stored program concept, the CPU's parts and the fetch-decode-execute cycle"),
    ("4.2", "4.2.4", "What affects CPU performance: clock speed, cores, cache"),
    ("4.2", "4.2.5", "Magnetic, optical and solid-state storage"),
    ("4.2", "4.2.6", "Cloud and other contemporary storage"),
    ("4.2", "4.2.7", "Embedded systems"),
    ("4.3", "4.3.1", "Truth tables for AND, OR and NOT"),
    ("4.3", "4.3.2", "Writing a logic statement for a problem"),
    ("4.4", "4.4.1", "What an operating system is and what it manages"),
    ("4.4", "4.4.2", "Utility software"),
    ("4.4", "4.4.3", "Software used to simulate and model the real world"),
    ("4.4", "4.4.4", "System software and application software"),
    ("4.5", "4.5.1", "High-level and low-level languages and their uses"),
    ("4.5", "4.5.2", "Assemblers, compilers and interpreters"),
    // 5 Communication and the internet
    ("5.1", "5.1.1", "Why computers are networked"),
    ("5.1", "5.1.2", "LAN, WAN, PAN, client-server, peer-to-peer"),
    ("5.1", "5.1.3", "Wired and wireless connectivity"),
    ("5.1", "5.1.4", "Data speeds in bits per second"),
    ("5.1", "5.1.5", "Network protocols and why they are needed"),
    ("5.1", "5.1.6", "Packets and the four-layer TCP/IP stack"),
    ("5.1", "5.1.7", "Bus, ring, star and mesh topologies"),
    ("5.1", "5.1.8", "Mobile standards: 3G, 4G and beyond"),
    ("5.2", "5.2.1", "Network security: validation and authentication"),
    ("5.2", "5.2.2", "Security of cloud storage"),
    ("5.2", "5.2.3", "Forms of cyber attack, technical and behavioural"),
    ("5.2", "5.2.4", "Finding vulnerabilities: penetration testing, ethical hacking, audits"),
    ("5.2", "5.2.5", "Protecting systems: design, code, review, audit trails, secure operation"),
    ("5.3", "5.3.1", "What the internet is and how it is structured"),
    ("5.3", "5.3.2", "The world wide web and its components"),
    ("5.3", "5.3.3", "IPv4 and IPv6 addressing"),
    ("5.3", "5.3.4", "Modem, router, switch, wireless access point"),
    // 6 The bigger picture
    ("6.1", "6.1.1", "Environmental impact of technology"),
    ("6.1", "6.1.2", "Ethical impact: privacy, inclusion, professionalism"),
    ("6.1", "6.1.3", "Legal impact: intellectual property, patents, licensing, data protection"),
    ("6.1", "6.1.4", "Emerging trends: quantum, DNA and nano computing, AI"),
];

/// Further Pure Mathematics 4PM1. Ten sections, each with lettered statements
/// A, B, C... in the "what students need to learn" column of the
/// specification (Issue 1, January 2016). 43 in all, sequence checked.
pub const FPM: &[(&str, &str, &str)] = &[
    ("1a", "1.A", "The exponential and logarithmic functions and their graphs"),
    ("1a", "1.B", "The laws of indices and logarithms, including change of base"),
    ("1b", "1.C", "Manipulating surds"),
    ("1b", "1.D", "Rationalising the denominator"),
    ("2", "2.A", "Manipulating quadratic expressions: factorising, completing the square"),
    ("2", "2.B", "The roots of a quadratic and the discriminant"),
    ("2", "2.C", "Functions of the roots: sum and product"),
    ("3a", "3.A", "Algebraic division"),
    ("3a", "3.B", "The factor and remainder theorems"),
    ("3a", "3.C", "Solving equations, including one linear with one quadratic"),
    ("3b", "3.D", "Linear and quadratic inequalities"),
    ("3c", "3.E", "Linear inequalities in two variables, graphically"),
    ("4", "4.A", "Graphs of polynomials and rational functions"),
    ("4", "4.B", "Solving equations and inequalities from graphs"),
    ("5", "5.A", "Sigma notation"),
    ("5", "5.B", "Arithmetic and geometric series, including the sum to infinity"),
    ("6", "6.A", "The binomial series for (1 + x) to the power n"),
    ("7", "7.A", "Adding and subtracting coplanar vectors"),
    ("7", "7.B", "Components and resolved parts"),
    ("7", "7.C", "Magnitude of a vector"),
    ("7", "7.D", "Position vectors"),
    ("7", "7.E", "Unit vectors"),
    ("7", "7.F", "Proving simple geometric properties with vectors"),
    ("8", "8.A", "Distance between two points"),
    ("8", "8.B", "The point dividing a line in a given ratio"),
    ("8", "8.C", "Gradient of a line through two points"),
    ("8", "8.D", "The equation of a straight line"),
    ("8", "8.E", "Parallel and perpendicular lines"),
    ("9a", "9.A", "Differentiating and integrating sums of powers of x, sin ax, cos ax, e to the ax"),
    ("9a", "9.B", "Product, quotient and chain rules"),
    ("9c", "9.C", "Kinematics, and areas and volumes by integration"),
    ("9b", "9.D", "Stationary and turning points"),
    ("9b", "9.E", "Maxima and minima"),
    ("9b", "9.F", "Tangents and normals"),
    ("9d", "9.G", "Rates of change, including connected rates"),
    ("10a", "10.A", "Radians, arc length and sector area"),
    ("10a", "10.B", "The three ratios for any angle, and their graphs"),
    ("10b", "10.C", "Problems in two and three dimensions"),
    ("10b", "10.D", "The sine and cosine rules"),
    ("10c", "10.E", "The identity sin squared plus cos squared equals one"),
    ("10c", "10.F", "tan as sin over cos"),
    ("10c", "10.G", "The addition formulae"),
    ("10c", "10.H", "Solving trigonometric equations in a given interval"),
];
/// The table for a subject, if it has been broken down to statement level.
pub fn table_for(subject_id: &str) -> &'static [(&'static str, &'static str, &'static str)] {
    match subject_id {
        "maths" => MATHS,
        "bio" => BIO,
        "chem" => CHEM,
        "phys" => PHYS,
        "econ" => ECON,
        "bus" => BUS,
        "cs" => CS,
        "fpm" => FPM,
        _ => &[],
    }
}

/// Every statement belonging to one topic, in specification order.
pub fn for_topic(subject_id: &str, topic_code: &str) -> Vec<(String, String)> {
    table_for(subject_id).iter()
        .filter(|(t, _, _)| *t == topic_code)
        .map(|(_, c, l)| ((*c).to_string(), (*l).to_string()))
        .collect()
}

/// Whether a subject has been broken down to statement level yet.
pub fn has_statements(subject_id: &str) -> bool {
    !table_for(subject_id).is_empty()
}

/// Whether a statement is examined only in the separate science, not Double
/// Award: Pearson suffixes those B, C or P.
pub fn separate_only(code: &str) -> bool {
    code.ends_with(['B', 'C', 'P'])
}
